# Permalinks
permalink:        /blog/:year/:month/:day/:title.html

# Highlighter
highlighter:      pygments

# Setup
title:            Joseph Billingsley
tagline:          Software developer in progress
description:	    Website and blog of Joseph Billingsley
url:              www.josephbillingsley.co.uk

author:
  name:           'Joseph Billingsley'
  url:            https://twitter.com/josephbillingsley

paginate:         3

sass:
  style: compressed

# Custom vars
version:          0.0.1